import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "ru" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionaries
const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Navigation
    "nav.home": "Главная",
    "nav.cases": "Кейсы",
    "nav.services": "Услуги",
    "nav.ai_products": "AI-продукты",
    "nav.calculator": "Калькулятор",
    "nav.about": "Обо мне",
    "nav.faq": "FAQ",
    "nav.contact": "Связаться",
    "nav.blog": "Блог",
    
    // Hero
    "hero.badge": "AI & Digital Production Expert",
    "hero.title_1": "AI-продукты",
    "hero.title_2": " и сайты, которые приносят заявки",
    "hero.subtitle": "Создаю AI-решения и премиальные сайты под услуги. Также веду продюсирование и вертикальный контент — Reels, Shorts, TikTok. Беру на себя большую часть работы.",
    "hero.cta_primary": "Обсудить проект",
    "hero.cta_secondary": "Смотреть кейсы",
    "hero.stat_years": "Года в digital",
    "hero.stat_projects": "Проектов",
    "hero.stat_ai": "В каждом решении",
    "hero.stat_response": "Ответ на заявку",
    "hero.how_i_work": "Как я работаю",
    "hero.step_1_title": "Анализ",
    "hero.step_1_desc": "Изучаю задачу и контекст",
    "hero.step_2_title": "Стратегия",
    "hero.step_2_desc": "Предлагаю решение",
    "hero.step_3_title": "Реализация",
    "hero.step_3_desc": "Создаю продукт",
    "hero.step_4_title": "Поддержка",
    "hero.step_4_desc": "Помогаю масштабировать",
    
    // What I Do
    "whatido.label": "Направления",
    "whatido.title": "Что я делаю",
    "whatido.subtitle": "AI-продукты и сайты — основной фокус. Плюс продюсирование контента для тех, кому нужны охваты. Беру на себя большую часть работы.",
    "whatido.more": "Подробнее",
    "whatido.websites": "Сайты под услуги",
    "whatido.websites_desc": "Премиальные сайты, которые повышают доверие и собирают заявки. Быстро и без лишней сложности.",
    "whatido.ai_products": "AI-продукты",
    "whatido.ai_products_desc": "Чат-боты, ассистенты, автоматизация. Снимаю рутину и ускоряю работу вашей команды.",
    "whatido.vertical_content": "Вертикальный контент",
    "whatido.vertical_content_desc": "Reels, Shorts, TikTok — монтаж и продюсирование роликов, которые удерживают внимание.",
    "whatido.ai_video": "AI-видео",
    "whatido.ai_video_desc": "Визуал нового уровня с AI-генерацией. Включает продюсирование и профессиональный монтаж.",
    "whatido.consulting": "Консалтинг",
    "whatido.consulting_desc": "Аудит процессов и стратегия внедрения AI. Помогаю понять, где технологии принесут максимум пользы.",
    
    // Services Preview
    "services_preview.title": "Чем я могу помочь",
    "services_preview.subtitle": "AI-продукты, сайты под услуги и вертикальный контент. Беру на себя большую часть работы.",
    "services_preview.all": "Все услуги",
    
    // Featured Cases
    "cases.featured_title": "Избранные кейсы",
    "cases.featured_subtitle": "Проекты, которые демонстрируют мой подход к созданию цифровых продуктов",
    "cases.all": "Все кейсы",
    "cases.title": "Кейсы",
    "cases.subtitle": "Проекты, которые демонстрируют силу AI и цифровых технологий в решении реальных задач",
    "cases.all_projects": "Все проекты",
    "cases.montage": "Монтаж",
    "cases.producing": "Продюсирование",
    "cases.ai_video": "AI-видео",
    "cases.ai_products": "AI-продукты",
    "cases.vibe_coding": "Vibe coding",
    "cases.montage_reels": "Монтаж Reels & Shorts",
    "cases.complex_projects": "Комплексные проекты",
    "cases.empty": "Проектов в этой категории пока нет",
    
    // Services
    "services.title": "Услуги",
    "services.subtitle": "От вертикального контента до AI-продуктов и сайтов. Беру на себя большую часть работы — вы занимаетесь своим делом.",
    "services.price_note": "Финальная стоимость зависит от задачи — рассчитывается индивидуально",
    "services.details": "Подробнее",
    "services.how_choose": "Как выбрать услугу?",
    "services.how_choose_subtitle": "Всё зависит от вашей задачи. Вот простая навигация:",
    "services.popular": "Популярные услуги",
    "services.quick_start": "Быстрый старт",
    "services.quick_start_subtitle": "Самые востребованные услуги с подробным описанием и примерами работ",
    
    // Why Trust Me
    "trust.label": "Подход",
    "trust.title": "Почему мне ",
    "trust.title_accent": "доверяют",
    "trust.subtitle": "Я не продаю технологии ради технологий. Моя задача — снять с вас головную боль и сделать так, чтобы вы получили результат без погружения в детали.",
    "trust.quote": "Можно оставить заявку без созвона — я сам уточню детали и предложу решение",
    "trust.item_1_title": "Беру на себя процесс",
    "trust.item_1_desc": "Вы занимаетесь своим делом — я беру на себя техническую реализацию и головную боль",
    "trust.item_2_title": "Понимаю бизнес-задачи",
    "trust.item_2_desc": "Не просто делаю, а разбираюсь зачем. Предлагаю решения, которые работают на результат",
    "trust.item_3_title": "Прозрачная работа",
    "trust.item_3_desc": "Понятные сроки, честная коммуникация и регулярные отчёты на всех этапах",
    "trust.item_4_title": "Поддержка после запуска",
    "trust.item_4_desc": "Не бросаю проект после сдачи. Помогаю развивать и адаптировать под новые задачи",
    
    // Contact
    "contact.label": "Контакты",
    "contact.title": "Давайте обсудим ",
    "contact.title_accent": "ваш проект",
    "contact.subtitle": "Расскажите о вашей задаче — я подготовлю предварительную оценку и предложу возможные решения. Консультация бесплатна.",
    "contact.name": "Имя",
    "contact.name_placeholder": "Как к вам обращаться?",
    "contact.email": "Email",
    "contact.email_placeholder": "your@email.com",
    "contact.message": "О проекте",
    "contact.message_placeholder": "Расскажите о вашей задаче, сроках и бюджете",
    "contact.submit": "Отправить заявку",
    "contact.submitting": "Отправка...",
    "contact.response_time": "Обычно отвечаю в течение 24 часов",
    "contact.success": "Сообщение отправлено! Свяжусь с вами в ближайшее время.",
    
    // CTA
    "cta.title": "Готовы начать проект?",
    "cta.subtitle": "Расскажите о вашей задаче — подготовлю предложение в течение 24 часов",
    "cta.primary": "Обсудить проект",
    "cta.secondary": "Рассчитать стоимость",
    
    // Footer
    "footer.rights": "Все права защищены",
    "footer.nav": "Навигация",
    "footer.services": "Услуги",
    "footer.contacts": "Контакты",
    "footer.social": "Соцсети",
    "footer.made_with": "Сделано с использованием AI",
    
    // Exit Popup
    "popup.title": "Подождите!",
    "popup.subtitle": "Получите бесплатную консультацию по вашему проекту",
    "popup.cta": "Получить консультацию",
    "popup.close": "Нет, спасибо",
    
    // About Page
    "about.title": "Обо мне",
    "about.intro": "Я занимаюсь AI-решениями и цифровым продакшеном. Помогаю бизнесу автоматизировать рутину, создавать контент и запускать digital-продукты.",
    "about.intro_2": "Моя задача — снять с вас большую часть работы. Вы занимаетесь бизнесом, а я беру на себя техническую реализацию: от первой встречи до запуска готового продукта. Работаю прозрачно, соблюдаю сроки и всегда на связи.",
    "about.telegram_cta": "Написать в Telegram",
    "about.view_cases": "Смотреть кейсы",
    "about.what_i_do": "Чем я занимаюсь",
    "about.what_i_do_subtitle": "Специализируюсь на пересечении технологий и контента — там, где AI встречается с бизнесом",
    "about.ai_products": "AI-продукты",
    "about.ai_products_desc": "Чат-боты, автоматизация процессов, интеграция нейросетей в бизнес-процессы",
    "about.digital_production": "Digital Production",
    "about.digital_production_desc": "Контент-стратегия, Reels, вертикальный контент для привлечения клиентов",
    "about.web_dev": "Веб-разработка",
    "about.web_dev_desc": "Сайты-визитки, лендинги, корпоративные порталы под ключ",
    "about.consulting": "Консалтинг",
    "about.consulting_desc": "AI-аудит бизнеса, стратегии автоматизации, обучение команды",
    "about.what_you_get": "Что вы получите, работая со мной",
    "about.what_you_get_desc": "Я беру на себя весь технический процесс — от постановки задачи до финального результата. Вам не нужно разбираться в технологиях или координировать подрядчиков.",
    "about.benefit_1": "Полный цикл работы — от стратегии до готового продукта",
    "about.benefit_2": "Снимаю с вас головную боль по технической реализации",
    "about.benefit_3": "Прозрачная коммуникация и понятные сроки",
    "about.benefit_4": "Опыт в разных нишах — понимаю специфику бизнеса",
    "about.benefit_5": "Современный стек технологий и AI-инструменты",
    "about.benefit_6": "Поддержка после запуска проекта",
    "about.years_in_digital": "года в digital",
    "about.experience_desc_1": "За это время я работал с разными нишами: от локального бизнеса до технологических стартапов. Понимаю, как устроен бизнес изнутри.",
    "about.experience_desc_2": "Мой подход — делать просто и эффективно. Без лишнего усложнения, с фокусом на результат, который можно измерить.",
    "about.my_channels": "Мои каналы",
    "about.channels_subtitle": "Делюсь опытом в AI, автоматизации и создании digital-продуктов. Подписывайтесь там, где вам удобнее.",
    "about.subscribe": "Подписаться",
    "about.watch": "Смотреть",
    "about.channel_content": "Что публикую: AI-кейсы, гайды по автоматизации, разборы продуктов, закулисье работы",
    "about.ready_to_discuss": "Готовы обсудить проект?",
    "about.ready_to_discuss_desc": "Напишите мне, и мы разберём вашу задачу. Расскажу, как могу помочь, и предложу варианты решения — без обязательств.",
    "about.other_contacts": "Другие способы связи",
    "about.telegram_notes": "Заметки о работе, инсайты и закулисье проектов",
    "about.youtube_desc": "Разборы кейсов, гайды по AI и автоматизации",
    "about.instagram_desc": "Вертикальный контент, процесс работы",
    "about.tiktok_desc": "Короткие видео, тренды и эксперименты",
    
    // FAQ Page
    "faq.title": "FAQ",
    "faq.subtitle": "Ответы на часто задаваемые вопросы о моих услугах и процессе работы",
    "faq.not_found": "Не нашли ответ?",
    "faq.not_found_desc": "Свяжитесь со мной, и я с удовольствием отвечу на любые вопросы",
    "faq.contact_btn": "Связаться",
    "faq.q1": "Какие услуги вы предоставляете?",
    "faq.a1": "Я специализируюсь на создании AI-продуктов, вайб кодинге (быстрая разработка MVP), монтаже вертикальных видео и продюсировании контента. Также создаю премиальные лендинги и сайты под ключ для бизнеса в сфере услуг.",
    "faq.q2": "Сколько стоят ваши услуги?",
    "faq.a2": "Стоимость зависит от сложности проекта. Монтаж Reels — от 3000₽, продюсирование — от 5000₽, AI-видео — от 7000₽, создание AI продукта — от 8000₽, премиальный лендинг — от 25000₽. Напишите для точной оценки.",
    "faq.q3": "Как долго занимает разработка проекта?",
    "faq.a3": "Монтаж вертикальных видео — 2-5 дней. Вайб кодинг MVP — 1-2 недели. AI-продукт — 2-4 недели. Премиальный лендинг или сайт под ключ — 2-4 недели. Сроки согласовываем индивидуально.",
    "faq.q4": "Что такое вайб кодинг?",
    "faq.a4": "Вайб кодинг — это современный подход к быстрой разработке веб-приложений с использованием AI-инструментов. Позволяет создать работающий MVP за недели вместо месяцев, экономя время и бюджет.",
    "faq.q5": "Работаете ли вы с проектами под ключ?",
    "faq.a5": "Да, я предоставляю полный цикл услуг — от концепции до запуска. Создание AI продукта, продюсирование контента, разработка сайта под ключ — всё в одном месте без координации множества подрядчиков.",
    "faq.q6": "Какие AI-продукты вы создаёте?",
    "faq.a6": "Чат-боты для бизнеса, автоматизации на Make/Zapier, системы генерации контента, AI-ассистенты для обработки заявок. Любые решения на базе современных нейросетей для автоматизации бизнес-процессов.",
    "faq.q7": "Можно ли доработать существующий продукт?",
    "faq.a7": "Конечно. Работаю как с проектами с нуля, так и с доработкой существующих решений. Провожу аудит, выявляю узкие места и предлагаю план улучшений.",
    "faq.q8": "Как начать сотрудничество?",
    "faq.a8": "Напишите мне через форму на странице контактов или в Telegram. Опишите вашу задачу — монтаж видео, AI-продукт, сайт или что-то другое. Отвечу в течение 24 часов.",
    
    // Contacts Page
    "contacts.title": "Давайте обсудим ваш проект",
    "contacts.subtitle": "Напишите мне — отвечу в течение 24 часов. Без обязательств, просто разберёмся, чем могу помочь.",
    "contacts.telegram": "Telegram",
    "contacts.telegram_desc": "Быстрый ответ",
    "contacts.instagram": "Instagram",
    "contacts.instagram_desc": "Direct сообщения",
    "contacts.leave_request": "Оставить заявку",
    "contacts.leave_request_desc": "Расскажите о задаче — я свяжусь для обсуждения деталей",
    "contacts.your_name": "Как вас зовут?",
    "contacts.how_contact": "Как связаться?",
    "contacts.contact_placeholder": "Telegram, email или телефон",
    "contacts.about_task": "Расскажите о задаче",
    "contacts.task_placeholder": "Что нужно сделать? Какие сроки? Есть ли референсы?",
    "contacts.detail_hint": "Чем подробнее опишете — тем точнее смогу оценить",
    "contacts.send_request": "Отправить заявку",
    "contacts.sending": "Отправка...",
    "contacts.response_time": "Время ответа",
    "contacts.up_to_24h": "до 24 часов",
    "contacts.response_note": "Обычно отвечаю быстрее. В выходные возможна задержка.",
    "contacts.location": "Локация",
    "contacts.remote": "Удалённо",
    "contacts.location_note": "Работаю с клиентами по всему миру. Созвоны в удобное для вас время.",
    "contacts.no_obligation": "Без обязательств",
    "contacts.no_obligation_desc": "Первый разговор — это просто знакомство. Вы ничего не должны, пока сами не решите работать.",
    "contacts.how_work": "Как происходит работа",
    "contacts.how_work_subtitle": "Простой и прозрачный процесс от первого контакта до результата",
    "contacts.step": "Шаг",
    "contacts.step1_title": "Знакомство",
    "contacts.step1_desc": "Созваниваемся на 15-30 минут. Вы рассказываете о задаче, я задаю уточняющие вопросы",
    "contacts.step2_title": "Предложение",
    "contacts.step2_desc": "В течение 24-48 часов готовлю детальное предложение со сроками и стоимостью",
    "contacts.step3_title": "Старт работы",
    "contacts.step3_desc": "После согласования начинаем работу. Вы получаете доступ к процессу и промежуточные результаты",
    "contacts.what_to_prepare": "Что подготовить до старта",
    "contacts.what_to_prepare_subtitle": "Эти вещи помогут быстрее понять задачу и дать точную оценку",
    "contacts.prepare1_title": "Опишите задачу",
    "contacts.prepare1_desc": "Что нужно сделать? Какую проблему решаем? Чем конкретнее — тем точнее оценка",
    "contacts.prepare2_title": "Определите сроки",
    "contacts.prepare2_desc": "Есть ли дедлайн? Это влияет на приоритизацию и возможность взяться за проект",
    "contacts.prepare3_title": "Соберите примеры",
    "contacts.prepare3_desc": "Референсы, которые нравятся. Ссылки на конкурентов. Это ускорит понимание",
    "contacts.dont_worry": "Не переживайте, если чего-то нет — разберёмся вместе",
    
    // AI Products Page
    "ai_products.title": "AI-продукты",
    "ai_products.subtitle": "Готовые решения на основе искусственного интеллекта. Не нужно изобретать велосипед — берите работающие инструменты и адаптируйте под себя.",
    "ai_products.free_audit": "Бесплатный AI-аудит",
    "ai_products.products_in_category": "Продукты в категории",
    "ai_products.coming_soon": "Продукты в этой категории скоро появятся",
    "ai_products.get_demo": "Получить демо",
    "ai_products.dont_know_where_to_start": "Не знаете, с чего начать?",
    "ai_products.audit_desc": "Пройдите бесплатный AI-аудит — заполните короткую анкету о вашем бизнесе, и я подготовлю персональный план автоматизации с конкретными рекомендациями.",
    "ai_products.take_audit": "Пройти AI-аудит",
    "ai_products.need_custom": "Нужно кастомное решение?",
    "ai_products.custom_desc": "Разработаем AI-продукт под ваши специфические задачи",
    "ai_products.discuss_project": "Обсудить проект",
    
    // Calculator Page
    "calc.title": "Рассчитать проект",
    "calc.subtitle": "Заполните бриф и получите предварительную оценку стоимости и сроков",
    "calc.select_service": "Выберите тип услуги",
    "calc.what_need": "Что вам нужно?",
    "calc.volume_timing": "Объём и сроки",
    "calc.clarify_details": "Уточните детали проекта",
    "calc.quantity": "Количество",
    "calc.urgency": "Срочность",
    "calc.standard": "Стандартный",
    "calc.standard_time": "2-4 недели",
    "calc.fast": "Ускоренный",
    "calc.fast_time": "1-2 недели",
    "calc.urgent": "Срочный",
    "calc.urgent_time": "до 1 недели",
    "calc.references_budget": "Референсы и бюджет",
    "calc.help_understand": "Помогите мне лучше понять задачу",
    "calc.reference_link": "Ссылка на пример (необязательно)",
    "calc.reference_placeholder": "https://example.com или ссылка на видео",
    "calc.reference_hint": "Покажите, что вам нравится — это поможет точнее оценить проект",
    "calc.budget_range": "Бюджетная вилка",
    "calc.your_contacts": "Ваши контакты",
    "calc.for_proposal": "Для отправки предложения",
    "calc.your_name": "Ваше имя",
    "calc.your_email": "Ваш email",
    "calc.additional_details": "Дополнительные детали (опционально)",
    "calc.additional_placeholder": "Что ещё важно учесть?",
    "calc.back": "Назад",
    "calc.next": "Далее",
    "calc.get_estimate": "Получить оценку",
    "calc.getting_estimate": "Отправка...",
    "calc.preliminary_estimate": "Предварительная оценка",
    "calc.budget": "Бюджет",
    "calc.timeline": "Сроки",
    "calc.complexity": "Сложность",
    "calc.complexity_low": "Низкая",
    "calc.complexity_medium": "Средняя",
    "calc.complexity_high": "Высокая",
    "calc.request_sent": "Заявка отправлена!",
    "calc.thanks": "Спасибо за интерес к сотрудничеству. Я свяжусь с вами в течение 24 часов для обсуждения деталей.",
    "calc.your_estimate": "Ваша предварительная оценка",
    "calc.what_next": "Что дальше?",
    "calc.next_step_1": "Я изучу вашу заявку и подготовлю детальное предложение",
    "calc.next_step_2": "Созвонимся для обсуждения деталей и уточнения требований",
    "calc.next_step_3": "Согласуем финальную стоимость, сроки и приступим к работе",
    "calc.calculate_another": "Рассчитать другой проект",
    "calc.reels": "Монтаж Reels / видео",
    "calc.website": "Разработка сайта",
    "calc.ai_bot": "AI-бот / автоматизация",
    "calc.content_strategy": "Контент-стратегия",
    "calc.branding": "Брендинг / дизайн",
    "calc.consulting": "Консалтинг",
    "calc.videos": "видео",
    "calc.pages": "страниц",
    "calc.scenarios": "сценариев",
    "calc.months": "месяцев",
    "calc.elements": "элементов",
    "calc.hours": "часов",
    
    // Video Modal
    "video_modal.want_same": "Хотите такой же результат?",
    "video_modal.discuss": "Обсудить проект",
    
    // Case Detail
    "case_detail.all_cases": "Все кейсы",
    "case_detail.task": "Задача",
    "case_detail.solution": "Решение",
    "case_detail.result": "Результат",
    "case_detail.gallery": "Галерея",
    "case_detail.deliverables": "Что было сделано",
    "case_detail.technologies": "Технологии",
    "case_detail.want_same": "Хотите так же?",
    "case_detail.want_same_desc": "Обсудим ваш проект и найдём лучшее решение",
    "case_detail.next_case": "Следующий кейс",
    
    // Service Detail
    "service_detail.all_services": "Все услуги",
    "service_detail.process": "Процесс работы",
    "service_detail.faq": "Частые вопросы",
    "service_detail.includes": "Что входит",
    "service_detail.want_order": "Хотите заказать?",
    "service_detail.want_order_desc": "Обсудим вашу задачу и подготовлю предложение",
    "service_detail.next_service": "Другая услуга",
    
    // Admin
    "admin.dashboard": "Дашборд",
    "admin.content_management": "Управление контентом сайта",
    "admin.cases": "Кейсы",
    "admin.services": "Услуги",
    "admin.ai_products": "AI-продукты",
    "admin.blog": "Статьи блога",
    "admin.portfolio": "Портфолио",
    "admin.quick_actions": "Быстрые действия",
    "admin.management": "Управление",
    "admin.media_library": "Медиа-библиотека",
    "admin.site_settings": "Настройки сайта",
    "admin.seo_settings": "SEO настройки",
    "admin.logout": "Выйти",
    "admin.to_site": "На сайт",
    
    // Common
    "common.from": "от",
    "common.learn_more": "Подробнее",
    "common.back": "Назад",
    "common.loading": "Загрузка...",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.cases": "Cases",
    "nav.services": "Services",
    "nav.ai_products": "AI Products",
    "nav.calculator": "Calculator",
    "nav.about": "About",
    "nav.faq": "FAQ",
    "nav.contact": "Contact",
    "nav.blog": "Blog",
    
    // Hero
    "hero.badge": "AI & Digital Production Expert",
    "hero.title_1": "AI products",
    "hero.title_2": " and websites that drive leads",
    "hero.subtitle": "I create AI solutions and premium service websites. I also handle content production and vertical content — Reels, Shorts, TikTok. I take care of most of the work.",
    "hero.cta_primary": "Discuss Project",
    "hero.cta_secondary": "View Cases",
    "hero.stat_years": "Years in digital",
    "hero.stat_projects": "Projects",
    "hero.stat_ai": "In every solution",
    "hero.stat_response": "Response time",
    "hero.how_i_work": "How I work",
    "hero.step_1_title": "Analysis",
    "hero.step_1_desc": "Study the task and context",
    "hero.step_2_title": "Strategy",
    "hero.step_2_desc": "Propose a solution",
    "hero.step_3_title": "Implementation",
    "hero.step_3_desc": "Build the product",
    "hero.step_4_title": "Support",
    "hero.step_4_desc": "Help scale",
    
    // What I Do
    "whatido.label": "Directions",
    "whatido.title": "What I do",
    "whatido.subtitle": "AI products and websites are the main focus. Plus content production for those who need reach. I handle most of the work.",
    "whatido.more": "Learn more",
    "whatido.websites": "Service Websites",
    "whatido.websites_desc": "Premium websites that build trust and collect leads. Fast and without unnecessary complexity.",
    "whatido.ai_products": "AI Products",
    "whatido.ai_products_desc": "Chatbots, assistants, automation. I remove routine and speed up your team's work.",
    "whatido.vertical_content": "Vertical Content",
    "whatido.vertical_content_desc": "Reels, Shorts, TikTok — editing and producing videos that hold attention.",
    "whatido.ai_video": "AI Video",
    "whatido.ai_video_desc": "Next-level visuals with AI generation. Includes production and professional editing.",
    "whatido.consulting": "Consulting",
    "whatido.consulting_desc": "Process audit and AI implementation strategy. I help understand where technology brings maximum value.",
    
    // Services Preview
    "services_preview.title": "How I can help",
    "services_preview.subtitle": "AI products, service websites and vertical content. I handle most of the work.",
    "services_preview.all": "All services",
    
    // Featured Cases
    "cases.featured_title": "Featured Cases",
    "cases.featured_subtitle": "Projects showcasing my approach to digital product creation",
    "cases.all": "All cases",
    "cases.title": "Cases",
    "cases.subtitle": "Projects demonstrating the power of AI and digital technologies in solving real problems",
    "cases.all_projects": "All projects",
    "cases.montage": "Editing",
    "cases.producing": "Production",
    "cases.ai_video": "AI Video",
    "cases.ai_products": "AI Products",
    "cases.vibe_coding": "Vibe coding",
    "cases.montage_reels": "Reels & Shorts Editing",
    "cases.complex_projects": "Complex Projects",
    "cases.empty": "No projects in this category yet",
    
    // Services
    "services.title": "Services",
    "services.subtitle": "From vertical content to AI products and websites. I handle most of the work — you focus on your business.",
    "services.price_note": "Final cost depends on the task — calculated individually",
    "services.details": "Learn more",
    "services.how_choose": "How to choose a service?",
    "services.how_choose_subtitle": "It all depends on your task. Here's a simple guide:",
    "services.popular": "Popular Services",
    "services.quick_start": "Quick Start",
    "services.quick_start_subtitle": "Most requested services with detailed descriptions and examples",
    
    // Why Trust Me
    "trust.label": "Approach",
    "trust.title": "Why clients ",
    "trust.title_accent": "trust me",
    "trust.subtitle": "I don't sell technology for technology's sake. My goal is to take the headache off your shoulders and deliver results without you diving into details.",
    "trust.quote": "You can leave a request without a call — I'll clarify the details and propose a solution myself",
    "trust.item_1_title": "I take over the process",
    "trust.item_1_desc": "You focus on your business — I handle the technical implementation and headaches",
    "trust.item_2_title": "I understand business goals",
    "trust.item_2_desc": "I don't just execute — I understand why. I propose solutions that work for results",
    "trust.item_3_title": "Transparent work",
    "trust.item_3_desc": "Clear timelines, honest communication, and regular updates at all stages",
    "trust.item_4_title": "Post-launch support",
    "trust.item_4_desc": "I don't abandon projects after delivery. I help develop and adapt to new tasks",
    
    // Contact
    "contact.label": "Contacts",
    "contact.title": "Let's discuss ",
    "contact.title_accent": "your project",
    "contact.subtitle": "Tell me about your task — I'll prepare a preliminary estimate and suggest possible solutions. Consultation is free.",
    "contact.name": "Name",
    "contact.name_placeholder": "How should I address you?",
    "contact.email": "Email",
    "contact.email_placeholder": "your@email.com",
    "contact.message": "About the project",
    "contact.message_placeholder": "Tell me about your task, timeline and budget",
    "contact.submit": "Send Request",
    "contact.submitting": "Sending...",
    "contact.response_time": "Usually respond within 24 hours",
    "contact.success": "Message sent! I'll get back to you soon.",
    
    // CTA
    "cta.title": "Ready to start a project?",
    "cta.subtitle": "Tell me about your task — I'll prepare a proposal within 24 hours",
    "cta.primary": "Discuss Project",
    "cta.secondary": "Calculate Cost",
    
    // Footer
    "footer.rights": "All rights reserved",
    "footer.nav": "Navigation",
    "footer.services": "Services",
    "footer.contacts": "Contacts",
    "footer.social": "Social",
    "footer.made_with": "Made with AI",
    
    // Exit Popup
    "popup.title": "Wait!",
    "popup.subtitle": "Get a free consultation on your project",
    "popup.cta": "Get Consultation",
    "popup.close": "No, thanks",
    
    // About Page
    "about.title": "About me",
    "about.intro": "I work with AI solutions and digital production. I help businesses automate routine, create content and launch digital products.",
    "about.intro_2": "My goal is to take most of the work off your shoulders. You focus on business, I handle the technical implementation: from the first meeting to launching the finished product. I work transparently, meet deadlines and am always in touch.",
    "about.telegram_cta": "Message on Telegram",
    "about.view_cases": "View cases",
    "about.what_i_do": "What I do",
    "about.what_i_do_subtitle": "I specialize at the intersection of technology and content — where AI meets business",
    "about.ai_products": "AI Products",
    "about.ai_products_desc": "Chatbots, process automation, integration of neural networks into business processes",
    "about.digital_production": "Digital Production",
    "about.digital_production_desc": "Content strategy, Reels, vertical content to attract customers",
    "about.web_dev": "Web Development",
    "about.web_dev_desc": "Business cards, landing pages, corporate portals turnkey",
    "about.consulting": "Consulting",
    "about.consulting_desc": "AI audit, automation strategies, team training",
    "about.what_you_get": "What you get working with me",
    "about.what_you_get_desc": "I take over the entire technical process — from task setting to the final result. You don't need to understand technology or coordinate contractors.",
    "about.benefit_1": "Full cycle — from strategy to finished product",
    "about.benefit_2": "I take the technical implementation headache off your shoulders",
    "about.benefit_3": "Transparent communication and clear timelines",
    "about.benefit_4": "Experience in different niches — I understand business specifics",
    "about.benefit_5": "Modern tech stack and AI tools",
    "about.benefit_6": "Support after project launch",
    "about.years_in_digital": "years in digital",
    "about.experience_desc_1": "During this time I've worked with different niches: from local business to tech startups. I understand how business works from inside.",
    "about.experience_desc_2": "My approach is to keep things simple and effective. No unnecessary complications, focused on measurable results.",
    "about.my_channels": "My channels",
    "about.channels_subtitle": "I share experience in AI, automation and digital products. Subscribe where convenient.",
    "about.subscribe": "Subscribe",
    "about.watch": "Watch",
    "about.channel_content": "What I post: AI cases, automation guides, product reviews, behind the scenes",
    "about.ready_to_discuss": "Ready to discuss a project?",
    "about.ready_to_discuss_desc": "Write to me and we'll break down your task. I'll tell you how I can help and suggest solutions — no obligations.",
    "about.other_contacts": "Other ways to contact",
    "about.telegram_notes": "Notes about work, insights and behind the scenes",
    "about.youtube_desc": "Case studies, AI and automation guides",
    "about.instagram_desc": "Vertical content, work process",
    "about.tiktok_desc": "Short videos, trends and experiments",
    
    // FAQ Page
    "faq.title": "FAQ",
    "faq.subtitle": "Answers to frequently asked questions about my services and work process",
    "faq.not_found": "Didn't find an answer?",
    "faq.not_found_desc": "Contact me and I'll be happy to answer any questions",
    "faq.contact_btn": "Contact",
    "faq.q1": "What services do you provide?",
    "faq.a1": "I specialize in creating AI products, vibe coding (rapid MVP development), vertical video editing and content production. I also create premium landing pages and turnkey websites for service businesses.",
    "faq.q2": "How much do your services cost?",
    "faq.a2": "Cost depends on project complexity. Reels editing — from $40, production — from $60, AI video — from $90, AI product — from $100, premium landing — from $300. Contact for exact estimate.",
    "faq.q3": "How long does project development take?",
    "faq.a3": "Vertical video editing — 2-5 days. Vibe coding MVP — 1-2 weeks. AI product — 2-4 weeks. Premium landing or turnkey website — 2-4 weeks. Timelines are agreed individually.",
    "faq.q4": "What is vibe coding?",
    "faq.a4": "Vibe coding is a modern approach to rapid web application development using AI tools. It allows creating a working MVP in weeks instead of months, saving time and budget.",
    "faq.q5": "Do you work on turnkey projects?",
    "faq.a5": "Yes, I provide a full cycle of services — from concept to launch. AI product creation, content production, turnkey website development — all in one place without coordinating multiple contractors.",
    "faq.q6": "What AI products do you create?",
    "faq.a6": "Business chatbots, Make/Zapier automations, content generation systems, AI assistants for request processing. Any solutions based on modern neural networks for business process automation.",
    "faq.q7": "Can you improve an existing product?",
    "faq.a7": "Of course. I work both on projects from scratch and on improving existing solutions. I conduct an audit, identify bottlenecks and propose an improvement plan.",
    "faq.q8": "How to start cooperation?",
    "faq.a8": "Write to me through the contact form or Telegram. Describe your task — video editing, AI product, website or something else. I'll respond within 24 hours.",
    
    // Contacts Page
    "contacts.title": "Let's discuss your project",
    "contacts.subtitle": "Write to me — I'll respond within 24 hours. No obligations, just figuring out how I can help.",
    "contacts.telegram": "Telegram",
    "contacts.telegram_desc": "Quick response",
    "contacts.instagram": "Instagram",
    "contacts.instagram_desc": "Direct messages",
    "contacts.leave_request": "Leave a request",
    "contacts.leave_request_desc": "Tell about the task — I'll contact you to discuss details",
    "contacts.your_name": "What's your name?",
    "contacts.how_contact": "How to contact you?",
    "contacts.contact_placeholder": "Telegram, email or phone",
    "contacts.about_task": "Tell about the task",
    "contacts.task_placeholder": "What needs to be done? What are the deadlines? Any references?",
    "contacts.detail_hint": "The more detailed — the more accurate the estimate",
    "contacts.send_request": "Send request",
    "contacts.sending": "Sending...",
    "contacts.response_time": "Response time",
    "contacts.up_to_24h": "up to 24 hours",
    "contacts.response_note": "Usually respond faster. Delays possible on weekends.",
    "contacts.location": "Location",
    "contacts.remote": "Remote",
    "contacts.location_note": "I work with clients worldwide. Calls at your convenient time.",
    "contacts.no_obligation": "No obligations",
    "contacts.no_obligation_desc": "First conversation is just getting acquainted. You owe nothing until you decide to work together.",
    "contacts.how_work": "How work happens",
    "contacts.how_work_subtitle": "Simple and transparent process from first contact to result",
    "contacts.step": "Step",
    "contacts.step1_title": "Introduction",
    "contacts.step1_desc": "We have a 15-30 minute call. You tell about the task, I ask clarifying questions",
    "contacts.step2_title": "Proposal",
    "contacts.step2_desc": "Within 24-48 hours I prepare a detailed proposal with timeline and cost",
    "contacts.step3_title": "Work begins",
    "contacts.step3_desc": "After agreement we start work. You get access to the process and intermediate results",
    "contacts.what_to_prepare": "What to prepare before starting",
    "contacts.what_to_prepare_subtitle": "These things help understand the task faster and give accurate estimate",
    "contacts.prepare1_title": "Describe the task",
    "contacts.prepare1_desc": "What needs to be done? What problem are we solving? The more specific — the more accurate the estimate",
    "contacts.prepare2_title": "Define timeline",
    "contacts.prepare2_desc": "Is there a deadline? This affects prioritization and ability to take on the project",
    "contacts.prepare3_title": "Gather examples",
    "contacts.prepare3_desc": "References you like. Competitor links. This speeds up understanding",
    "contacts.dont_worry": "Don't worry if something's missing — we'll figure it out together",
    
    // AI Products Page
    "ai_products.title": "AI Products",
    "ai_products.subtitle": "Ready-made solutions based on artificial intelligence. No need to reinvent the wheel — take working tools and adapt them to your needs.",
    "ai_products.free_audit": "Free AI Audit",
    "ai_products.products_in_category": "Products in category",
    "ai_products.coming_soon": "Products in this category coming soon",
    "ai_products.get_demo": "Get demo",
    "ai_products.dont_know_where_to_start": "Don't know where to start?",
    "ai_products.audit_desc": "Take a free AI audit — fill out a short questionnaire about your business, and I'll prepare a personalized automation plan with specific recommendations.",
    "ai_products.take_audit": "Take AI Audit",
    "ai_products.need_custom": "Need a custom solution?",
    "ai_products.custom_desc": "We'll develop an AI product for your specific tasks",
    "ai_products.discuss_project": "Discuss project",
    
    // Calculator Page
    "calc.title": "Calculate project",
    "calc.subtitle": "Fill out the brief and get a preliminary cost and timeline estimate",
    "calc.select_service": "Select service type",
    "calc.what_need": "What do you need?",
    "calc.volume_timing": "Volume and timing",
    "calc.clarify_details": "Clarify project details",
    "calc.quantity": "Quantity",
    "calc.urgency": "Urgency",
    "calc.standard": "Standard",
    "calc.standard_time": "2-4 weeks",
    "calc.fast": "Accelerated",
    "calc.fast_time": "1-2 weeks",
    "calc.urgent": "Urgent",
    "calc.urgent_time": "up to 1 week",
    "calc.references_budget": "References and budget",
    "calc.help_understand": "Help me better understand the task",
    "calc.reference_link": "Reference link (optional)",
    "calc.reference_placeholder": "https://example.com or video link",
    "calc.reference_hint": "Show what you like — this helps estimate the project more accurately",
    "calc.budget_range": "Budget range",
    "calc.your_contacts": "Your contacts",
    "calc.for_proposal": "To send the proposal",
    "calc.your_name": "Your name",
    "calc.your_email": "Your email",
    "calc.additional_details": "Additional details (optional)",
    "calc.additional_placeholder": "What else is important to consider?",
    "calc.back": "Back",
    "calc.next": "Next",
    "calc.get_estimate": "Get estimate",
    "calc.getting_estimate": "Sending...",
    "calc.preliminary_estimate": "Preliminary estimate",
    "calc.budget": "Budget",
    "calc.timeline": "Timeline",
    "calc.complexity": "Complexity",
    "calc.complexity_low": "Low",
    "calc.complexity_medium": "Medium",
    "calc.complexity_high": "High",
    "calc.request_sent": "Request sent!",
    "calc.thanks": "Thank you for your interest. I'll contact you within 24 hours to discuss the details.",
    "calc.your_estimate": "Your preliminary estimate",
    "calc.what_next": "What's next?",
    "calc.next_step_1": "I'll review your request and prepare a detailed proposal",
    "calc.next_step_2": "We'll have a call to discuss details and clarify requirements",
    "calc.next_step_3": "We'll agree on final cost, timeline and start work",
    "calc.calculate_another": "Calculate another project",
    "calc.reels": "Reels / Video editing",
    "calc.website": "Website development",
    "calc.ai_bot": "AI bot / Automation",
    "calc.content_strategy": "Content strategy",
    "calc.branding": "Branding / Design",
    "calc.consulting": "Consulting",
    "calc.videos": "videos",
    "calc.pages": "pages",
    "calc.scenarios": "scenarios",
    "calc.months": "months",
    "calc.elements": "elements",
    "calc.hours": "hours",
    
    // Video Modal
    "video_modal.want_same": "Want the same result?",
    "video_modal.discuss": "Discuss project",
    
    // Case Detail
    "case_detail.all_cases": "All cases",
    "case_detail.task": "Task",
    "case_detail.solution": "Solution",
    "case_detail.result": "Result",
    "case_detail.gallery": "Gallery",
    "case_detail.deliverables": "What was done",
    "case_detail.technologies": "Technologies",
    "case_detail.want_same": "Want the same?",
    "case_detail.want_same_desc": "Let's discuss your project and find the best solution",
    "case_detail.next_case": "Next case",
    
    // Service Detail
    "service_detail.all_services": "All services",
    "service_detail.process": "Work process",
    "service_detail.faq": "FAQ",
    "service_detail.includes": "What's included",
    "service_detail.want_order": "Want to order?",
    "service_detail.want_order_desc": "Let's discuss your task and I'll prepare a proposal",
    "service_detail.next_service": "Another service",
    
    // Admin
    "admin.dashboard": "Dashboard",
    "admin.content_management": "Content management",
    "admin.cases": "Cases",
    "admin.services": "Services",
    "admin.ai_products": "AI Products",
    "admin.blog": "Blog Posts",
    "admin.portfolio": "Portfolio",
    "admin.quick_actions": "Quick Actions",
    "admin.management": "Management",
    "admin.media_library": "Media Library",
    "admin.site_settings": "Site Settings",
    "admin.seo_settings": "SEO Settings",
    "admin.logout": "Logout",
    "admin.to_site": "To Site",
    
    // Common
    "common.from": "from",
    "common.learn_more": "Learn more",
    "common.back": "Back",
    "common.loading": "Loading...",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("language") as Language;
      if (saved && (saved === "ru" || saved === "en")) {
        return saved;
      }
      // Detect browser language
      const browserLang = navigator.language.toLowerCase();
      return browserLang.startsWith("ru") ? "ru" : "en";
    }
    return "ru";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
